<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Logrr.Contracts\Logrr.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Logrr.Core\Logrr.Core.csproj" />
  </ItemGroup>

</Project>
