<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Logrr.Contracts\Logrr.Contracts.csproj" />
    <ProjectReference Include="..\Logrr.Core\Logrr.Core.csproj" />
  </ItemGroup>

</Project>
